import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
        {/* <link href="https://fonts.googleapis.com/css2?family=Monoton&display=swap" rel="stylesheet" /> */}
        <link
          href="https://fonts.googleapis.com/css2?family=Lobster&family=Oswald&family=Anton&family=Righteous&family=Bungee&family=Pacifico&family=Fredoka&family=Monoton&family=Fredericka+the+Great&family=Black+Ops+One&family=Ruslan+Display&family=Orbitron&family=Bangers&family=Cinzel+Decorative&family=Chewy&family=Creepster&family=Faster+One&family=Zilla+Slab+Highlight&family=Unica+One&family=Sonsie+One&family=Abril+Fatface&family=Chicle&family=Shrikhand&family=Cinzel+Decorative&family=Rye&family=Arvo&family=Zilla+Slab&family=Crete+Round&family=Josefin+Slab&family=Bevan&family=Alfa+Slab+One&family=Slabo+27px&family=Ultra&family=Vast+Shadow&family=Caudex&family=Patua+One&family=Bree+Serif&family=Aleo&family=Libre+Baskerville&family=Caveat&family=Dancing+Script&family=Amatic+SC&family=Indie+Flower&family=Patrick+Hand&family=Sacramento&family=Shadows+Into+Light&family=Satisfy&family=Alex+Brush&family=Fira+Code&family=JetBrains+Mono&family=Source+Code+Pro&family=Inconsolata&family=Roboto+Mono&family=Space+Mono&family=IBM+Plex+Mono&family=Cousine&family=PT+Mono&family=Ubuntu+Mono&family=Courier+Prime&family=Yellowtail&family=Gloria+Hallelujah&family=Cedarville+Cursive&family=Style+Script&family=Cookie&family=Coming+Soon&family=Great+Vibes&family=Luckiest+Guy&family=Reenie+Beanie&family=Kristi&family=Just+Another+Hand&family=Homemade+Apple&family=Handlee&family=Architects+Daughter&family=Allura&family=Covered+By+Your+Grace&family=Rock+Salt&family=Zeyada&family=La+Belle+Aurore&family=Give+You+Glory&family=Cutive+Mono&family=Share+Tech+Mono&family=Oxygen+Mono&family=DM+Mono&family=Lekton&family=Syne+Mono&family=VT323&family=Overpass+Mono&family=Anonymous+Pro&family=Roboto+Slab&family=Playfair+Display&family=Merriweather&family=Lora&family=EB+Garamond&family=PT+Serif&family=Noto+Serif&family=Crimson+Text&family=Cormorant&family=Cormorant+Garamond&family=Roboto&family=Open+Sans&family=Lato&family=Montserrat&family=Poppins&family=Inter&family=Raleway&family=Nunito&family=Mulish&family=Bebas+Neue&family=Teko&family=Lilita+One&family=Archivo+Black&family=Passion+One&family=Racing+Sans+One&family=Titan+One&family=Federo&family=Ubuntu&family=Quicksand&family=Josefin+Sans&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
